# (C) James Haywood 2017
print ("Welcome to CrazyWords!")
noun1 =input("First, I need a noun. ")
verb1 =input("Now a verb. ")
adj1  =input("An adjective. ")
adv1  =input("An adverb. ")
noun2 =input("Another noun. ")
name =input ("A name. ")
num =input ("A number. ")
anyth =input("Anything! ")
print ("Generating story...")
print ("One day, a", noun1, "was sitting on the sidewalk. Then a person came along and noticed it, and then he", verb1, "it. Soon after the person felt", adj1, " ")
print ("The person ran like", adv1, "and ran into another", noun1,"with the name of", name, ". It then promptly stabbed the person", num, "times. It then", anyth,".")
thing = input("")
