import time
while True:
    print ("     *        * ")
    print ("    ***      ***")
    print ("   *****    *****")
    print ("  *******  *******")
    print ("  *******  *******  ")
    print ("   *****    *****")
    print ("    ***      *** ")
    print ("     *        *")
    time.sleep(0.10)
    print ("          *        * ")
    print ("         ***      ***")
    print ("        *****    *****")
    print ("       *******  *******")
    print ("       *******  *******  ")
    print ("        *****    *****")
    print ("         ***      *** ")
    print ("          *        *")
    time.sleep(0.10)
    print ("               *        * ")
    print ("              ***      ***")
    print ("             *****    *****")
    print ("            *******  *******")
    print ("            *******  *******  ")
    print ("             *****    *****")
    print ("              ***      *** ")
    print ("               *        *")
    time.sleep(0.10)
    print ("          *        * ")
    print ("         ***      ***")
    print ("        *****    *****")
    print ("       *******  *******")
    print ("       *******  *******  ")
    print ("        *****    *****")
    print ("         ***      *** ")
    print ("          *        *")
    time.sleep(0.10)
    print ("     *        * ")
    print ("    ***      ***")
    print ("   *****    *****")
    print ("  *******  *******")
    print ("  *******  *******  ")
    print ("   *****    *****")
    print ("    ***      *** ")
    print ("     *        *")
    print(" ")
    time.sleep(0.10)
