#!/bin/bash

# CYBERPATRIOT 2018 UBUNTU VM SCRIPT
# IMPORTANT: Must be run with root priviledges to opeate correctly
# This script is based off of a heatmap for CP-XI and may not work as intended in the future.

# STEP 1: REMOVE PROHIBITED SOFTWARE AND FILES

apt-get install sed

apt-get remove john-the-ripper
apt-get remove nitko
apt-get remove ophcrack
apt-get remove freeciv
apt-get remove frostwire
apt-get remove hydra
apt-get remove kismet
apt-get remove medusa
apt-get remove minetest
apt-get remove vuze
apt-get remove samba
apt-get remove vnc4server && apt-get remove vncserver && apt-get remove tightvncserver


# STEP 2: SECURITY AND ACCOUNT POLICIES

ufw enable

apt-get install libpam-cracklib

echo -e "Cyberpatriot1!\nCyberpatriot1!" | passwd root

# thicc acct security changes start

echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf

sed -i 's/99999/90/g' /etc/login.defs
sed -i 's/PASS_MIN_DAYS\t0/PASS_MIN_DAYS\t10/g' /etc/login.defs
sed -i 's/PASS_WARN_AGE\t*/PASS_WARN_AGE\t7\n# /g' /etc/login.defs

echo "auth required pam_tally2.so deny=5 onerr=fail unlock_time=1800" >> /etc/pam.d/common-auth

sed -i 's/password    requisite    pam_cracklib.so retry=3 minlen=8 difok=3/password    requisite    pam_cracklib.so retry=3 minlen=10 difok=3 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1/g' /etc/pam.d/common-password

sed -i 's/password    [success=1 default=ignore]    pam_unix.so obscure use_authtok try_first_pass sha512/password    [success=1 default=ignore]    pam_unix.so obscure use_authtok try_first_pass sha512 remember=5 minlen=10
/g' /etc/pam.d/common-password

# thicc acct security changes end

# fix common ownership issues
chown root:root /home
chmod 755 /home
chown root:root /root
chown 700 /root

#disable ssh root login (very common)
echo "PermitRootLogin no" >> /etc/ssh/sshd_config

cd /home


# step 3: other shit

#kill unauthorized files
find . -name "*.mp3" -type f -delete
find . -name "*.wav" -type f -delete
find . -name "*.wma" -type f -delete
find . -name "*.aac" -type f -delete

find . -name "*.mp4" -type f -delete
find . -name "*.mov" -type f -delete
find . -name "*.avi" -type f -delete

#step 4 - rattle off stuff for user to look at and act upon

#part 5 - BOOBY TRAP THE STALEMATE BUTTO- nah jk update apps and OS

apt-get update
apt-get upgrade --fix-missing

echo "Script complete, please reboot to finalize."



