print ("Hello, and welcome to GenericRestaraunt (TM). I will be your waiter tonight")
print("What's your name?")
name = input("> ")
print('Welcome', name)
print("Alright, what would you like to drink?")
print("---MENU---")
print("Water")
print("Milk")
print("Sand")
drink = input("> ")
print("Certainly. What about the meal?")
print("---MENU---")
print("Bat Sautee")
print("Dead Meat")
print("Something gross involving Kale")
food = input("> ")
print('Certainly, Mr. Poor Taste', name)
print("I will be right back with your food.")
print ("*ELEVATOR MUSIC*")
print('Here is your drink, some', drink)
print("Here, let me pour it out all over that hideous outfit.")
print("Your outfit is ruined!")
print('And here is your', food)
print("The waiter dumps it on your head and leaves.")
weapon = input("Quick! Decide on a weapon to apprehend him! > ")
print('You chase after the waiter with your', weapon)
print("You use it on him, and he drops to the floor, dead.")
whatchasay = input("What do you tell the cops when they surely arrive? > ")
print('The cops arrive and you tell them', whatchasay, 'They nod understandedly and leave.')
yn = input("A voice booms from the loudspeakers above the restaurant door - NAME ANY ANIMAL! > ")
print ('A', yn , "drops out of the sky and devours you. THE END")
print ("Would you like to play again?")
playagain = input("> ")
print ("Hmm...", playagain," I don't want to do that. Bye!")
end = input("")


